version: "3"
services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 88:80
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    depends_on:
      - php-fpm
    ports:
      - 2345:5432
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: 'minio'
    ports:
      - 9090:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    entrypoint: sh
    command: -c 
      "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /usr/bin/minio server /data;
      "
    volumes:
      - ${DATA_PATH_HOST}/minio:/data
      - ./docker/minio/export:/export
      - ./docker/minio/config:/root/.minio
      - ./docker/minio/policies:/policies
